### ISSUE TITLE
Nullpointer Exception After creating java File and clicking Done button after creation

### ISSUE THREAD

**Issue by hirshi001** [Railroad-Team/Modding-IDE#36]
How it happens:
File > New > Class
Create class, choose file location
After pressing the Save button, a little popup window appears saying where the class was created, and then has a button which says Done.
After pressing the button, nothing happens, but there is a nullpointer exception which occurs on line 51 in the CreateNewJavaFile class.

**Comment by hirshi001** [comment]
Also happens when creating interfaces, i haven't checked with the rest though yet.

**Comment by jojo2357** [comment]
Wtf i fixed this like 6 hours ago

**Comment by hirshi001** [comment]
im afraid the error is still there. I just downloaded the code and tried it again, and still got the same problem

**Comment by jojo2357** [comment]
Yeah i think i know why

**Comment by hirshi001** [comment]
Yeah, line 25 in the AbstractNewFileWindow class. the makeWindow method shouldn't be called in the constructor method, cause then it doesn't exit it until the window is removed.

**Comment by saksham4106** [comment]
oops I will fix my jank code 😓

**Comment by jojo2357** [comment]
Im already there dw ab it
